import { Locale } from '@/lib/i18n/types';

export interface ApartmentItem {
  id: string;
  complex: string;
  complexSlug: 'abu-dhabi' | 'madina-residence';
  rooms: 1 | 2 | 3;
  roomsLabel: string;
  area: number;
  block: string;
  floor: string;
  priceM2: number;
  price: number;
  planImage: string;
  badge?: string;
  windowsView: Record<Locale, string>;
}

export const ALL_APARTMENTS: ApartmentItem[] = [
  // =========================================================================
  // 🏢 ЖК ABU DHABI ($1 650 / м²) — 13 вариантов (1-в-1 к чертежам)
  // =========================================================================
  {
    id: 'ad-1-4948',
    complex: 'ЖК Abu Dhabi',
    complexSlug: 'abu-dhabi',
    rooms: 1,
    roomsLabel: '1-комнатная',
    area: 49.48,
    block: 'Блок Б',
    floor: '2–14 этажи',
    priceM2: 1650,
    price: 81642,
    planImage: '/layouts/abu-dhabi/1%201room-abu.png',
    badge: 'Блок Б',
    windowsView: {
      ru: 'Во внутренний двор и парк',
      kg: 'Ички короого жана паркка',
      kz: 'Ішкі аулаға және саябаққа',
      uk: 'У внутрішній двір та парк',
      en: 'Inner courtyard & landscaped park',
      zh: '朝向中庭园林与城市绿意',
    },
  },
  {
    id: 'ad-1-4973',
    complex: 'ЖК Abu Dhabi',
    complexSlug: 'abu-dhabi',
    rooms: 1,
    roomsLabel: '1-комнатная',
    area: 49.73,
    block: 'Блок Б',
    floor: '2–14 этажи',
    priceM2: 1650,
    price: 82055,
    planImage: '/layouts/abu-dhabi/2%201room-abu.png',
    badge: 'Блок Б',
    windowsView: {
      ru: 'Восточная сторона, утреннее солнце',
      kg: 'Чыгыш тарап, таңкы күн',
      kz: 'Шығыс бағыт, таңғы күн',
      uk: 'Східна сторона, ранкове сонце',
      en: 'Eastern orientation, morning sunlight',
      zh: '正东朝向，清晨阳光充足',
    },
  },
  {
    id: 'ad-1-5088',
    complex: 'ЖК Abu Dhabi',
    complexSlug: 'abu-dhabi',
    rooms: 1,
    roomsLabel: '1-комнатная',
    area: 50.88,
    block: 'Блок А',
    floor: '2–14 этажи',
    priceM2: 1650,
    price: 83952,
    planImage: '/layouts/abu-dhabi/3%201room-abu.png',
    badge: 'Блок А',
    windowsView: {
      ru: 'Вид на Южную магистраль и горы',
      kg: 'Түштүк магистраль жана тоолор',
      kz: 'Оңтүстік магистраль және таулар',
      uk: 'Вид на Південну магістраль та гори',
      en: 'Southern Highway and mountain skyline',
      zh: '开阔南部景观大道与连绵山峦',
    },
  },
  {
    id: 'ad-1-5468',
    complex: 'ЖК Abu Dhabi',
    complexSlug: 'abu-dhabi',
    rooms: 1,
    roomsLabel: '1-комнатная',
    area: 54.68,
    block: 'Блок Б',
    floor: '2–14 этажи',
    priceM2: 1650,
    price: 90222,
    planImage: '/layouts/abu-dhabi/4%201room-abu.png',
    badge: 'Блок Б',
    windowsView: {
      ru: 'Панорамный вид во двор',
      kg: 'Короого панорамалык көрүнүш',
      kz: 'Аулаға панорамалық көрініс',
      uk: 'Панорамний вид у двір',
      en: 'Panoramic garden court view',
      zh: '高区全景内园视野',
    },
  },
  {
    id: 'ad-1-5562',
    complex: 'ЖК Abu Dhabi',
    complexSlug: 'abu-dhabi',
    rooms: 1,
    roomsLabel: '1-комнатная',
    area: 55.62,
    block: 'Блок Б',
    floor: '2–14 этажи',
    priceM2: 1650,
    price: 91773,
    planImage: '/layouts/abu-dhabi/5%201room-abu.png',
    badge: 'Блок Б',
    windowsView: {
      ru: 'Юго-восток, солнечная сторона',
      kg: 'Түштүк-чыгыш, күн тарап',
      kz: 'Оңтүстік-шығыс, күн түсетін жақ',
      uk: 'Південний схід, сонячна сторона',
      en: 'South-East sunny exposure',
      zh: '东南朝向，采光通透优渥',
    },
  },
  {
    id: 'ad-1-5805',
    complex: 'ЖК Abu Dhabi',
    complexSlug: 'abu-dhabi',
    rooms: 1,
    roomsLabel: '1-комнатная',
    area: 58.05,
    block: 'Блок Б',
    floor: '2–14 этажи',
    priceM2: 1650,
    price: 95783,
    planImage: '/layouts/abu-dhabi/6%201room-abu.png',
    badge: 'Блок Б',
    windowsView: {
      ru: 'Просторная евро-двушка с видом на парк',
      kg: 'Сейил бакка караган кенен евро-2 батир',
      kz: 'Саябаққа қараған кең евро-2 пәтер',
      uk: 'Простора євродвушка з видом на парк',
      en: 'Spacious Euro 2-room with park view',
      zh: '宽景轻奢格局，畅享生态公园美景',
    },
  },
  {
    id: 'ad-2-7830',
    complex: 'ЖК Abu Dhabi',
    complexSlug: 'abu-dhabi',
    rooms: 2,
    roomsLabel: '2-комнатная',
    area: 78.30,
    block: 'Блок Б',
    floor: '2–14 этажи',
    priceM2: 1650,
    price: 129195,
    planImage: '/layouts/abu-dhabi/1%202room-abu.png',
    badge: 'Блок Б',
    windowsView: {
      ru: 'Панорама гор Ала-Тоо',
      kg: 'Ала-Тоо тоолорунун панорамасы',
      kz: 'Ала-Тау панорамасы',
      uk: 'Панорама гір Ала-Тоо',
      en: 'Ala-Too Mountain Skyline',
      zh: '一线正对阿拉套山脉雪峰全景',
    },
  },
  {
    id: 'ad-2-7977',
    complex: 'ЖК Abu Dhabi',
    complexSlug: 'abu-dhabi',
    rooms: 2,
    roomsLabel: '2-комнатная',
    area: 79.77,
    block: 'Блок А',
    floor: '2–14 этажи',
    priceM2: 1650,
    price: 131621,
    planImage: '/layouts/abu-dhabi/2%202room-abu.png',
    badge: 'Блок А',
    windowsView: {
      ru: 'Двусторонняя: горы и внутренний двор',
      kg: 'Эки тараптуу: тоо жана короо',
      kz: 'Екі жақты: таулар мен аула',
      uk: 'Двостороння, гори та подвір’я',
      en: 'Dual-aspect: Mountains & Courtyard',
      zh: '南北通透：远眺雪山与近享园林',
    },
  },
  {
    id: 'ad-2-8026',
    complex: 'ЖК Abu Dhabi',
    complexSlug: 'abu-dhabi',
    rooms: 2,
    roomsLabel: '2-комнатная',
    area: 80.26,
    block: 'Блок А',
    floor: '2–14 этажи',
    priceM2: 1650,
    price: 132429,
    planImage: '/layouts/abu-dhabi/3%202room-abu.png',
    badge: 'Блок А',
    windowsView: {
      ru: 'Вид на город и горы',
      kg: 'Шаар жана тоолор көрүнүшү',
      kz: 'Қала мен таулар көрінісі',
      uk: 'Вид на місто та гори',
      en: 'Cityscape & Mountain panorama',
      zh: '繁华都市天际线与壮丽山景交相辉映',
    },
  },
  {
    id: 'ad-2-8159',
    complex: 'ЖК Abu Dhabi',
    complexSlug: 'abu-dhabi',
    rooms: 2,
    roomsLabel: '2-комнатная',
    area: 81.59,
    block: 'Блок Б',
    floor: '2–14 этажи',
    priceM2: 1650,
    price: 134624,
    planImage: '/layouts/abu-dhabi/4%202room-abu.png',
    badge: 'Блок Б',
    windowsView: {
      ru: 'Панорамные витражи на юг',
      kg: 'Түштүккө караган витраж терезелер',
      kz: 'Оңтүстікке қараған витраждар',
      uk: 'Панорамні вітражі на південь',
      en: 'South-facing floor-to-ceiling glazing',
      zh: '南向超大采光全景落地窗',
    },
  },
  {
    id: 'ad-2-8358',
    complex: 'ЖК Abu Dhabi',
    complexSlug: 'abu-dhabi',
    rooms: 2,
    roomsLabel: '2-комнатная',
    area: 83.58,
    block: 'Блок А',
    floor: '2–14 этажи',
    priceM2: 1650,
    price: 137907,
    planImage: '/layouts/abu-dhabi/5%202room-abu.png',
    badge: 'Блок А',
    windowsView: {
      ru: 'Юго-запад, закат и горы',
      kg: 'Түштүк-батыш, күн батышы жана тоолор',
      kz: 'Оңтүстік-батыс, күн батуы мен таулар',
      uk: 'Південний захід, захід сонця і гори',
      en: 'South-West sunset & mountain views',
      zh: '西南朝向，落日余晖与雪山画卷',
    },
  },
  {
    id: 'ad-2-8399',
    complex: 'ЖК Abu Dhabi',
    complexSlug: 'abu-dhabi',
    rooms: 2,
    roomsLabel: '2-комнатная',
    area: 83.99,
    block: 'Блок А',
    floor: '2–14 этажи',
    priceM2: 1650,
    price: 138584,
    planImage: '/layouts/abu-dhabi/6%202room-abu.png',
    badge: 'Блок А',
    windowsView: {
      ru: 'Угловая с панорамным обзором 270°',
      kg: '270° панорамалык көрүнүшү бар бурчтук',
      kz: '270° панорамалық шолуы бар бұрыштық',
      uk: 'Кутова з панорамою 270°',
      en: 'Corner unit with 270° panoramic view',
      zh: '转角270度环幕天际全视野',
    },
  },
  {
    id: 'ad-3-11932',
    complex: 'ЖК Abu Dhabi',
    complexSlug: 'abu-dhabi',
    rooms: 3,
    roomsLabel: '3-комнатная',
    area: 119.32,
    block: 'Блок Б',
    floor: '2–14 этажи',
    priceM2: 1650,
    price: 196878,
    planImage: '/layouts/abu-dhabi/1%203room-abu.png',
    badge: 'Блок Б • Премиум',
    windowsView: {
      ru: 'Пентхаус-формат: панорама на горы и город',
      kg: 'Пентхаус форматы: тоо жана шаар көрүнүшү',
      kz: 'Пентхаус форматы: таулар мен қала көрінісі',
      uk: 'Формат пентхауса: панорама на гори та місто',
      en: 'Penthouse-tier: 360° mountain & city view',
      zh: '顶奢大平层格局：360度城市与雪峰双重盛景',
    },
  },

  // =========================================================================
  // 🏢 ЖК MADINA RESIDENCE ($1 500 / м²) — 24 варианта
  // =========================================================================
  {
    id: 'mr-1-4359',
    complex: 'ЖК Madina Residence',
    complexSlug: 'madina-residence',
    rooms: 1,
    roomsLabel: '1-комнатная',
    area: 43.59,
    block: 'Блок А',
    floor: '2–14 этажи',
    priceM2: 1500,
    price: 65385,
    planImage: '/layouts/madina-residence/1%201room-madina.png',
    badge: 'Блок А',
    windowsView: {
      ru: 'Вид на благоустроенный зеленый двор',
      kg: 'Жашылдандырылган короого көрүнүш',
      kz: 'Көгалдандырылған аулаға көрініс',
      uk: 'Вид на зелений затишний двір',
      en: 'Courtyard landscaped greens view',
      zh: '朝向品质中庭园林绿意',
    },
  },
  {
    id: 'mr-1-4521',
    complex: 'ЖК Madina Residence',
    complexSlug: 'madina-residence',
    rooms: 1,
    roomsLabel: '1-комнатная',
    area: 45.21,
    block: 'Блок А',
    floor: '2–14 этажи',
    priceM2: 1500,
    price: 67815,
    planImage: '/layouts/madina-residence/2%201room-madina.png',
    badge: 'Блок А',
    windowsView: {
      ru: 'Восточная сторона, мягкий утренний свет',
      kg: 'Чыгыш тарап, таңкы жумшак жарык',
      kz: 'Шығыс бағыт, таңғы жарық',
      uk: 'Східна сторона, ранкове світло',
      en: 'Eastern light, quiet residential view',
      zh: '正东朝向，清晨柔和采光',
    },
  },
  {
    id: 'mr-1-4647',
    complex: 'ЖК Madina Residence',
    complexSlug: 'madina-residence',
    rooms: 1,
    roomsLabel: '1-комнатная',
    area: 46.47,
    block: 'Блок В',
    floor: '2–14 этажи',
    priceM2: 1500,
    price: 69705,
    planImage: '/layouts/madina-residence/3%201room-madina.png',
    badge: 'Блок В',
    windowsView: {
      ru: 'Вид на детскую и спортивную площадки',
      kg: 'Балдар жана спорт аянтчасына көрүнүш',
      kz: 'Балалар және спорт алаңына көрініс',
      uk: 'Вид на дитячий та спортивний майданчики',
      en: 'Overlooking kids playground & fitness zone',
      zh: '俯瞰社区全龄儿童及运动休闲区',
    },
  },
  {
    id: 'mr-1-4860',
    complex: 'ЖК Madina Residence',
    complexSlug: 'madina-residence',
    rooms: 1,
    roomsLabel: '1-комнатная',
    area: 48.60,
    block: 'Блок Б',
    floor: '2–14 этажи',
    priceM2: 1500,
    price: 72900,
    planImage: '/layouts/madina-residence/1%201room-madina.png',
    badge: 'Блок Б',
    windowsView: {
      ru: 'Тихий закрытый внутренний двор',
      kg: 'Тынч жабык ички короо',
      kz: 'Тыныш жабық ішкі аула',
      uk: 'Тихий закритий внутрішній двір',
      en: 'Peaceful private enclosed courtyard',
      zh: '完全人车分流静谧私密内院',
    },
  },
  {
    id: 'mr-1-4903',
    complex: 'ЖК Madina Residence',
    complexSlug: 'madina-residence',
    rooms: 1,
    roomsLabel: '1-комнатная',
    area: 49.03,
    block: 'Блок В',
    floor: '2–14 этажи',
    priceM2: 1500,
    price: 73545,
    planImage: '/layouts/madina-residence/2%201room-madina.png',
    badge: 'Блок В',
    windowsView: {
      ru: 'Правильная прямоугольная геометрия комнат',
      kg: 'Бөлмөлөрдүн туура жана ыңгайлуу формасы',
      kz: 'Бөлмелердің дұрыс тікбұрышты пішіні',
      uk: 'Правильне прямокутне планування',
      en: 'Classic rectangular living layout',
      zh: '方正通透户型无任何异形面积浪费',
    },
  },
  {
    id: 'mr-1-4914',
    complex: 'ЖК Madina Residence',
    complexSlug: 'madina-residence',
    rooms: 1,
    roomsLabel: '1-комнатная',
    area: 49.14,
    block: 'Блок В',
    floor: '2–14 этажи',
    priceM2: 1500,
    price: 73710,
    planImage: '/layouts/madina-residence/3%201room-madina.png',
    badge: 'Блок В',
    windowsView: {
      ru: 'Уютная спальня и просторная лоджия',
      kg: 'Жайлуу уктоочу бөлмө жана кенен лоджия',
      kz: 'Жайлы жатын бөлме және кең лоджия',
      uk: 'Затишна спальня та простора лоджія',
      en: 'Cozy master bedroom with deep balcony',
      zh: '静音主卧配备开敞生活景观阳台',
    },
  },
  {
    id: 'mr-1-4990',
    complex: 'ЖК Madina Residence',
    complexSlug: 'madina-residence',
    rooms: 1,
    roomsLabel: '1-комнатная',
    area: 49.90,
    block: 'Блок А',
    floor: '2–14 этажи',
    priceM2: 1500,
    price: 74850,
    planImage: '/layouts/madina-residence/1%201room-madina.png',
    badge: 'Блок А',
    windowsView: {
      ru: 'Удобная планировка с гардеробной и лоджией',
      kg: 'Гардероб жана балкон менен ыңгайлуу план',
      kz: 'Киім бөлмесі мен балконы бар ыңғайлы пәтер',
      uk: 'Планування з гардеробом та лоджією',
      en: 'Functional layout with walk-in closet',
      zh: '独立衣帽间与景观阳台格局',
    },
  },
  {
    id: 'mr-1-5001',
    complex: 'ЖК Madina Residence',
    complexSlug: 'madina-residence',
    rooms: 1,
    roomsLabel: '1-комнатная',
    area: 50.01,
    block: 'Блок Б',
    floor: '2–14 этажи',
    priceM2: 1500,
    price: 75015,
    planImage: '/layouts/madina-residence/2%201room-madina.png',
    badge: 'Блок Б',
    windowsView: {
      ru: 'Южная сторона, солнце в течение всего дня',
      kg: 'Түштүк тарап, күн бою жарык',
      kz: 'Оңтүстік бағыт, күні бойы жарық',
      uk: 'Південна сторона, сонце весь день',
      en: 'South-facing, all-day natural sunlight',
      zh: '正南朝向，全天候充足日照',
    },
  },
  {
    id: 'mr-1-5018',
    complex: 'ЖК Madina Residence',
    complexSlug: 'madina-residence',
    rooms: 1,
    roomsLabel: '1-комнатная',
    area: 50.18,
    block: 'Блок А',
    floor: '2–14 этажи',
    priceM2: 1500,
    price: 75270,
    planImage: '/layouts/madina-residence/3%201room-madina.png',
    badge: 'Блок А',
    windowsView: {
      ru: 'Вид на проспект Чуй и город',
      kg: 'Чүй кең көчөсүнө жана шаарга көрүнүш',
      kz: 'Шүй даңғылы мен қалаға көрініс',
      uk: 'Вид на проспект Чуй та місто',
      en: 'Chuy Avenue and city urban vistas',
      zh: '楚河大道繁盛市景与开阔视野',
    },
  },
  {
    id: 'mr-1-5315',
    complex: 'ЖК Madina Residence',
    complexSlug: 'madina-residence',
    rooms: 1,
    roomsLabel: '1-комнатная',
    area: 53.15,
    block: 'Блок В',
    floor: '2–14 этажи',
    priceM2: 1500,
    price: 79725,
    planImage: '/layouts/madina-residence/1%201room-madina.png',
    badge: 'Блок В',
    windowsView: {
      ru: 'Светлая евро-двушка с окнами на две стороны',
      kg: 'Эки тарапка караган жарык евро-2 батир',
      kz: 'Екі жаққа қараған жарық евро-2 пәтер',
      uk: 'Світла євродвушка з вікнами на дві сторони',
      en: 'Dual-side aspect bright layout',
      zh: '双向采光通风明亮宜居格局',
    },
  },
  {
    id: 'mr-1-5388',
    complex: 'ЖК Madina Residence',
    complexSlug: 'madina-residence',
    rooms: 1,
    roomsLabel: '1-комнатная',
    area: 53.88,
    block: 'Блок А',
    floor: '2–14 этажи',
    priceM2: 1500,
    price: 80820,
    planImage: '/layouts/madina-residence/2%201room-madina.png',
    badge: 'Блок А',
    windowsView: {
      ru: 'Просторная евро-двушка с большой кухней-гостиной',
      kg: 'Кенен ашкана-мейманканасы бар евро-2 батир',
      kz: 'Үлкен асүй-қонақ бөлмесі бар кең евро-2',
      uk: 'Велика кухня-вітальня, світлі вікна',
      en: 'Large living-kitchen area, panoramic windows',
      zh: '超大客餐厅一体化宽幕设计',
    },
  },
  {
    id: 'mr-1-5787',
    complex: 'ЖК Madina Residence',
    complexSlug: 'madina-residence',
    rooms: 1,
    roomsLabel: '1-комнатная',
    area: 57.87,
    block: 'Блок Б',
    floor: '2–14 этажи',
    priceM2: 1500,
    price: 86805,
    planImage: '/layouts/madina-residence/3%201room-madina.png',
    badge: 'Блок Б',
    windowsView: {
      ru: 'Угловая евро-двушка с панорамным остеклением',
      kg: 'Панорамалуу айнектелген бурчтук евро-2',
      kz: 'Панорамалық шынысы бар бұрыштық евро-2',
      uk: 'Кутова євродвушка з панорамним заскленням',
      en: 'Corner Euro 2-room with corner glazing',
      zh: '转角双面通透采光尊享居室',
    },
  },
  {
    id: 'mr-2-7100',
    complex: 'ЖК Madina Residence',
    complexSlug: 'madina-residence',
    rooms: 2,
    roomsLabel: '2-комнатная',
    area: 71.00,
    block: 'Блок А',
    floor: '2–14 этажи',
    priceM2: 1500,
    price: 106500,
    planImage: '/layouts/madina-residence/1%202room-madina.png',
    badge: 'Блок А',
    windowsView: {
      ru: 'Раздельные санузлы, вид на город',
      kg: 'Өзүнчө жуунучу бөлмөлөр, шаарга көрүнүш',
      kz: 'Бөлек жуынатын бөлмелер, қалаға көрініс',
      uk: 'Роздільні санвузли, вид на місто',
      en: 'Double bathrooms, cityscape panorama',
      zh: '干湿分离双卫设计，畅览城央天际线',
    },
  },
  {
    id: 'mr-2-7107',
    complex: 'ЖК Madina Residence',
    complexSlug: 'madina-residence',
    rooms: 2,
    roomsLabel: '2-комнатная',
    area: 71.07,
    block: 'Блок В',
    floor: '2–14 этажи',
    priceM2: 1500,
    price: 106605,
    planImage: '/layouts/madina-residence/2%202room-madina.png',
    badge: 'Блок В',
    windowsView: {
      ru: 'Идеальное зонирование: гостевая и спальная зоны',
      kg: 'Конок жана уктоочу аймактар туура бөлүнгөн',
      kz: 'Қонақ және ұйықтайтын аймақтары ыңғайлы бөлінген',
      uk: 'Ідеальне зонування: гостьова та спальна зони',
      en: 'Optimal zoning: private & entertaining areas',
      zh: '黄金功能动线设计：静享休憩与从容待客',
    },
  },
  {
    id: 'mr-2-7430',
    complex: 'ЖК Madina Residence',
    complexSlug: 'madina-residence',
    rooms: 2,
    roomsLabel: '2-комнатная',
    area: 74.30,
    block: 'Блок Б',
    floor: '2–14 этажи',
    priceM2: 1500,
    price: 111450,
    planImage: '/layouts/madina-residence/3%202room-madina.png',
    badge: 'Блок Б',
    windowsView: {
      ru: 'Южная сторона, солнечная гостиная с витражами',
      kg: 'Түштүк тарап, витраждуу жарык конок бөлмө',
      kz: 'Оңтүстік бағыт, витражды күн шуақты қонақ бөлме',
      uk: 'Південна сторона, вітражна світла вітальня',
      en: 'South-facing bright living room with glazing',
      zh: '朝南全明通透会客厅与落地飘窗',
    },
  },
  {
    id: 'mr-2-7453',
    complex: 'ЖК Madina Residence',
    complexSlug: 'madina-residence',
    rooms: 2,
    roomsLabel: '2-комнатная',
    area: 74.53,
    block: 'Блок А',
    floor: '2–14 этажи',
    priceM2: 1500,
    price: 111795,
    planImage: '/layouts/madina-residence/4%202room-madina.png',
    badge: 'Блок А',
    windowsView: {
      ru: 'Изолированные спальни и вид во двор',
      kg: 'Өзүнчө бөлмөлөр жана короого көрүнүш',
      kz: 'Оқшауланған бөлмелер және аулаға көрініс',
      uk: 'Ізольовані кімнати та вид у двір',
      en: 'Secluded master bedrooms with garden views',
      zh: '动静分区双卧设计，尊享安宁私密',
    },
  },
  {
    id: 'mr-2-7459',
    complex: 'ЖК Madina Residence',
    complexSlug: 'madina-residence',
    rooms: 2,
    roomsLabel: '2-комнатная',
    area: 74.59,
    block: 'Блок В',
    floor: '2–14 этажи',
    priceM2: 1500,
    price: 111885,
    planImage: '/layouts/madina-residence/5%202room-madina.png',
    badge: 'Блок В',
    windowsView: {
      ru: 'Два санузла, ниша под гардеробную',
      kg: 'Эки жуунучу бөлмө, гардероб үчүн атайын орун',
      kz: 'Екі жуынатын бөлме, киім бөлмесіне арналған орын',
      uk: 'Два санвузли, ніша під вбудовану шафу',
      en: 'Two bathrooms, walk-in closet alcove',
      zh: '主客双卫配置，预留独立大衣帽储物间',
    },
  },
  {
    id: 'mr-2-7474',
    complex: 'ЖК Madina Residence',
    complexSlug: 'madina-residence',
    rooms: 2,
    roomsLabel: '2-комнатная',
    area: 74.74,
    block: 'Блок В',
    floor: '2–14 этажи',
    priceM2: 1500,
    price: 112110,
    planImage: '/layouts/madina-residence/6%202room-madina.png',
    badge: 'Блок В',
    windowsView: {
      ru: 'Вид во внутренний ландшафтный двор',
      kg: 'Ички ландшафттуу короого көрүнүш',
      kz: 'Ішкі ландшафтты аулаға көрініс',
      uk: 'Вид у затишне внутрішнє подвір’я',
      en: 'Overlooking manicured landscape gardens',
      zh: '一线正对中央下沉式水景立体园林',
    },
  },
  {
    id: 'mr-2-7590',
    complex: 'ЖК Madina Residence',
    complexSlug: 'madina-residence',
    rooms: 2,
    roomsLabel: '2-комнатная',
    area: 75.90,
    block: 'Блок А',
    floor: '2–14 этажи',
    priceM2: 1500,
    price: 113850,
    planImage: '/layouts/madina-residence/7%202room-madina.png',
    badge: 'Блок А',
    windowsView: {
      ru: 'Двусторонняя распашонка восток-запад',
      kg: 'Чыгыш-батыш эки тараптуу батир',
      kz: 'Шығыс-батыс қос бағытты пәтер',
      uk: 'Двостороннє планування схід-захід',
      en: 'East-to-West cross ventilation layout',
      zh: '南北/东西大通透自然对流格局',
    },
  },
  {
    id: 'mr-2-8130',
    complex: 'ЖК Madina Residence',
    complexSlug: 'madina-residence',
    rooms: 2,
    roomsLabel: '2-комнатная',
    area: 81.30,
    block: 'Блок А',
    floor: '2–14 этажи',
    priceM2: 1500,
    price: 121950,
    planImage: '/layouts/madina-residence/8%202room-madina.png',
    badge: 'Блок А',
    windowsView: {
      ru: 'Большая кухня 18 м² и панорамная лоджия',
      kg: 'Чоң 18 м² ашкана жана кең балкон',
      kz: 'Үлкен 18 м² асүй және панорамалық лоджия',
      uk: 'Кухня 18 м² та панорамна лоджія',
      en: 'Spacious 18m² dining kitchen & wide balcony',
      zh: '18平米超阔餐厨厅配大面积景观落地窗',
    },
  },
  {
    id: 'mr-2-8131',
    complex: 'ЖК Madina Residence',
    complexSlug: 'madina-residence',
    rooms: 2,
    roomsLabel: '2-комнатная',
    area: 81.31,
    block: 'Блок В',
    floor: '2–14 этажи',
    priceM2: 1500,
    price: 121965,
    planImage: '/layouts/madina-residence/9%202room-madina.png',
    badge: 'Блок В',
    windowsView: {
      ru: 'Просторные квадратные спальни и лоджия',
      kg: 'Кенен чарчы уктоочу бөлмөлөр жана лоджия',
      kz: 'Кең шаршы пішінді жатын бөлмелер',
      uk: 'Просторі спальні правильної форми',
      en: 'Spacious square master suites with balcony',
      zh: '正气双主卧套间格局，起居从容大气',
    },
  },
  {
    id: 'mr-2-8378',
    complex: 'ЖК Madina Residence',
    complexSlug: 'madina-residence',
    rooms: 2,
    roomsLabel: '2-комнатная',
    area: 83.78,
    block: 'Блок А',
    floor: '2–14 этажи',
    priceM2: 1500,
    price: 125670,
    planImage: '/layouts/madina-residence/10%202room-madina.png',
    badge: 'Блок А',
    windowsView: {
      ru: 'Премиальная угловая планировка с видом на горы',
      kg: 'Тоолорго караган премиалдуу бурчтук батир',
      kz: 'Тауларға қараған премиум бұрыштық пәтер',
      uk: 'Преміальне кутове планування з видом на гори',
      en: 'Premium corner unit with mountain panorama',
      zh: '转角头等舱级雪山与都市双重视野',
    },
  },
  {
    id: 'mr-2-8409',
    complex: 'ЖК Madina Residence',
    complexSlug: 'madina-residence',
    rooms: 2,
    roomsLabel: '2-комнатная',
    area: 84.09,
    block: 'Блок В',
    floor: '2–14 этажи',
    priceM2: 1500,
    price: 126135,
    planImage: '/layouts/madina-residence/11%202room-madina.png',
    badge: 'Блок В',
    windowsView: {
      ru: 'Максимальная площадь 2-комнатных в комплексе',
      kg: 'Комплекстеги 2 бөлмөлүүлөрдүн эң чоң аянты',
      kz: 'Кешендегі ең үлкен 2 бөлмелі пәтер',
      uk: 'Найбільша площа 2-кімнатної квартири в комплексі',
      en: 'Largest 2-bedroom residence in the complex',
      zh: '全项目建筑面积最大奢雅二居室王牌户型',
    },
  },
  {
    id: 'mr-3-10848',
    complex: 'ЖК Madina Residence',
    complexSlug: 'madina-residence',
    rooms: 3,
    roomsLabel: '3-комнатная',
    area: 108.48,
    block: 'Блок Б',
    floor: '2–14 этажи',
    priceM2: 1500,
    price: 162720,
    planImage: '/layouts/madina-residence/1%203room-madina.png',
    badge: 'Блок Б • Для семьи',
    windowsView: {
      ru: 'Флагманская 3-комнатная квартира для большой семьи',
      kg: 'Чоң үй-бүлө үчүн флагмандык 3 бөлмөлүү батир',
      kz: 'Үлкен отбасы үшін флагмандық 3 бөлмелі пәтер',
      uk: 'Флагманська 3-кімнатна квартира для родини',
      en: 'Flagship family suite with 3 bedrooms & master bath',
      zh: '家族典藏大三居：三卧朝阳双卫全维阔景天幕',
    },
  },
];

export function getApartmentsByComplex(slug: 'abu-dhabi' | 'madina-residence') {
  return ALL_APARTMENTS.filter((a) => a.complexSlug === slug);
}

export function getApartmentById(id: string) {
  return ALL_APARTMENTS.find((a) => a.id === id);
}